app/models/profile.py
from sqlalchemy import event

from app import db
from .main import Language
from .security import User

#Model for Profile
class Profile(db.Model):
  __tablename__ = 'profile'
  id = db.Column(db.Integer, primary_key=True)
  userId = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
  languageId = db.Column(db.Integer, db.ForeignKey('language.id', ondelete='CASCADE'))
  firstName = db.Column(db.String(255), nullable=True)
  lastName = db.Column(db.String(255), nullable=True)
  about = db.Column(db.Text, nullable=True)

  def __repr__(self):
    return '<Profile {}>'.format(self.firstName, ' ', self.lastName)

# create profile
def create_profile_for_user(mapper, connection, user):
  connection.execute(Profile.__table__.insert().values(
    userId=user.id,
    languageId=Language.query.filter_by(isDefault=True).first().id
  ))
event.listen(User, 'after_insert', create_profile_for_user)

app/forms/profile.py
from flask_babel import _
from flask_wtf import FlaskForm
from wtforms import EmailField, SelectField, StringField, SubmitField
from wtforms.validators import Email, Length, Optional

#Form for Editing Profile
class EditProfileForm(FlaskForm):
  firstName = StringField(_('First Name'), validators=[Length(max=255)]) # Max length of db-column
  lastName = StringField(_('Last Name'), validators=[Length(max=255)]) # Max length of db-column
  email = EmailField(_('Email'), validators=[Optional(), Email()])
  languageId = SelectField(_('Language'), coerce=int)
  submit = SubmitField(_('Update'))

app/profile/__init__.py
from flask import Blueprint

bp = Blueprint('profile', __name__)

from . import routes

app/profile/routes.py
from flask import flash, redirect, render_template, request, url_for
from flask_babel import _
from flask_security import auth_required, current_user

from app import db
from app.forms import EditProfileForm
from app.models import Language, Profile
from app.profile import bp

#Route for Profile
@bp.route('/')
@auth_required()
def profile():
  profile = db.first_or_404(Profile.query.filter_by(userId=current_user.id))
  language = db.first_or_404(Language.query.filter_by(id=profile.languageId))
  points = current_user.total_points
  return render_template('profile/index.html', profile=profile, language=language, points=points)

#Route for Edit Profile
@bp.route('/edit/', methods=['GET', 'POST'])
@auth_required()
def edit():
  #Get the profile for the current user
  profile = db.first_or_404(Profile.query.filter_by(userId=current_user.id))
  #Create the form for the profile
  form = EditProfileForm(formdata=request.form, obj=profile, data={'email': current_user.email})
  form.languageId.choices = [(l.id, l.name) for l in Language.query.all()]
  if form.validate_on_submit():
    # POST
    if profile.userId != current_user.id:
      # Trying to change someone elses profile
      return redirect(url_for('profile.profile'))
    form.populate_obj(profile)
    current_user.email = form.email.data
    db.session.commit()
    flash(_('Profile successfully updated.'))
    return redirect(url_for('profile.profile'))
  return render_template('profile/edit.html', profile=profile, form=form)

app/templates/profile/edit.html
{% extends 'base.html' %}

{% block content %}
<section class="d-flex justify-content-center">
  <div class="col-md-6">
    <h1 class="text-left">{% block title %}{{ _('Edit Profile: ') }}{{ current_user.username }}{% endblock %}</h1>
    <form method="post">
      {{ form.hidden_tag() }}
      <div class="mb-3">
        {{ form.firstName.label(class='form-label') }}
        {{ form.firstName(class='form-control') }}
        {% for error in form.firstName.errors %}
        <span class="text-danger">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        {{ form.lastName.label(class='form-label') }}
        {{ form.lastName(class='form-control') }}
        {% for error in form.lastName.errors %}
        <span class="text-danger">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        {{ form.email.label(class='form-label') }}
        {{ form.email(class='form-control') }}
        {% for error in form.email.errors %}
        <span class="text-danger">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="mb-3">
        {{ form.languageId.label(class='form-label') }}
        {{ form.languageId(class='form-control') }}
        {% for error in form.languageId.errors %}
        <span class="text-danger">{{ error }}</span>
        {% endfor %}
      </div>
      {{ form.submit(class='btn btn-primary') }}
    </form>
  </div>
</section>
{% endblock %}

app/templates/profile/index.html
{% extends "base.html" %}
{% block content %}
<section class="d-flex justify-content-center">
  <div class="col-md-6">
    <h1 class="text-left">{{ _('Profile') }}</h1>

    <div class="d-flex justify-content-between">
      <p class="col-md-2 text-left">{{ _('Username') }}:</p>
      <p class="col-md-4 text-right">{{ current_user.username }}</p>
    </div>
    <div class="d-flex justify-content-between">
      <p class="col-md-2 text-left">{{ _('First Name') }}:</p>
      <p class="col-md-4 text-right">{{ profile.firstName }}</p>
    </div>
    <div class="d-flex justify-content-between">
      <p class="col-md-2 text-left">{{ _('Last Name') }}:</p>
      <p class="col-md-4 text-right">{{ profile.lastName }}</p>
    </div>
    <div class="d-flex justify-content-between">
      <p class="col-md-2 text-left">{{ _('Email') }}:</p>
      <p class="col-md-4 text-right">{{ current_user.email }}</p>
    </div>
    <div class="d-flex justify-content-between">
      <p class="col-md-2 text-left">{{ _('Language') }}:</p>
      <p class="col-md-4 text-right">{{ language.name }}</p>
    </div>
    <div class="d-flex justify-content-between">
      <p class="col-md-2 text-left">{{ _('Points') }}:</p>
      <p class="col-md-4 text-right">{{ points }}</p>
    </div>

    <a href="{{ url_for('security.change_password') }}" class="btn btn-primary">{{ _('Change Password') }}</a>
    <a href="{{ url_for('profile.edit') }}" class="btn btn-primary">{{ _('Edit Profile') }}</a>
  </div>
</section>
{% endblock %}